services:
  database:
    image: mariadb:latest
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  backend:
    env_file: ./.env
    ports:
      - ${BACKEND_PORT}:8080 
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - JAR_FILE=backend/build/libs/app.jar
