name: Backend Workflow

on:
  push:
    branches:
      - backend-dev

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: "password"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run all tests
        run: ./gradlew test